Google calendar integration
Simonmoush/nm4p_website pull request #9
Opened 2024-12-29 21:35 UTC by toots

This is a redo of https://github.com/NOLA-musicians-4-Palestine/nm4p_website/pull/2 with the latest changes merged.

2024-12-30 00:06 UTC, Simonmoush requested changes
These are the changes I'm gonna make before merging. Github seems to encourage me to make my comments a review so i did that, don't know if it's appropriate

2024-12-30 00:06 UTC, Simonmoush commented on .github/workflows/build-tools-container.yml
> +          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/tools:${{ github.ref_name }}
The checker says that the tag name cannot be upper case. I'm thinking we just transform the repo names to lower case for the tags.

2024-12-30 00:06 UTC, Simonmoush commented on .github/workflows/pages-deploy.yml
> -      - live
Want to keep this actually

2024-12-30 00:06 UTC, Simonmoush commented on .github/workflows/pages-deploy.yml
> +
want to keep all this

2024-12-30 00:06 UTC, Simonmoush commented on tools/generate_token.py
How does this file get run?

2025-01-06 13:27 UTC, toots commented on .github/workflows/build-tools-container.yml
> +          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/tools:${{ github.ref_name }}
I'd suggest to confirm that with an actual docker push. I wouldn't be surprised if that worked.

Otherwise, it looks like `github` actions' [limited functions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions) does not have one for converting the string to lowercase.

In this case, you'd need to convert the name to lowercase in. previous step, output the result and use it in this step.

2025-01-27 20:02 UTC, Simonmoush commented on .github/workflows/build-tools-container.yml
> +          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/tools:${{ github.ref_name }}
I'm not sure if this effectively checked, but I pushed to the branch google_calendar_integration and it did fail saying the name must be lower case.

2025-01-27 22:56 UTC, Simonmoush commented on .github/workflows/build-tools-container.yml
> +          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/tools:${{ github.ref_name }}
Ok this builds now. Pushes and pulls!

2025-08-01 16:44 UTC, merged